language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - mz2325@nyu.edu
    on_success: always
    on_failure: never

    recipients:
      - jn1404@nyu.edu
    on_success: always
    on_failure: always  
